services:

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    command: server /data --console-address ":9001"
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis_queue
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI web
    profiles: ["dev"]

  backend:
    build: ./backend
    container_name: fastapi_backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - database
      - minio
      - redis
  
  worker:
    build: ./backend
    container_name: arq_worker
    command: arq app.workers.arq_settings.WorkerSettings
    volumes:
      - ./backend:/app
    depends_on:
      - database
      - minio
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./frontend
    container_name: react_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app

    depends_on:
      - backend

  database:
    image: postgres:16
    container_name: realestate_db
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realestate
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  minio_data:
  redis_data: