"""

Revision ID: 5d2bc770f371
Revises: be23287da1bd
Create Date: 2026-07-27 18:58:56.271805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2bc770f371'
down_revision: Union[str, Sequence[str], None] = 'be23287da1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_prefix', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'key_prefix')
    # ### end Alembic commands ###
