"""

Revision ID: 686247ca1d0a
Revises: 1c36b568b59c
Create Date: 2026-05-22 19:54:51.310489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686247ca1d0a'
down_revision: Union[str, Sequence[str], None] = '1c36b568b59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('property_owners', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('property_owners', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('property_owners', 'document',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('property_owners', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_owners', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('property_owners', 'document',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('property_owners', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('property_owners', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
