"""

Revision ID: 737801b5a3ec
Revises: 9cae386b182c
Create Date: 2026-07-04 00:49:52.225287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '737801b5a3ec'
down_revision: Union[str, Sequence[str], None] = '9cae386b182c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('leads', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('leads', 'property_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'property_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('leads', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('leads', 'raw_data')
    # ### end Alembic commands ###
