"""

Revision ID: 93148d60e9e5
Revises: 5d2bc770f371
Create Date: 2026-07-27 19:07:10.209475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93148d60e9e5'
down_revision: Union[str, Sequence[str], None] = '5d2bc770f371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'permissions',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'permissions',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
