"""add property_sequences and composite slug unique

Revision ID: 9cae386b182c
Revises: e2a99564016f
Create Date: 2026-06-17 22:16:10.539104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cae386b182c'
down_revision: Union[str, Sequence[str], None] = 'e2a99564016f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_sequences',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'property_type')
    )
    op.drop_constraint(op.f('properties_slug_key'), 'properties', type_='unique')
    op.create_unique_constraint('uq_properties_tenant_slug', 'properties', ['tenant_id', 'slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_properties_tenant_slug', 'properties', type_='unique')
    op.create_unique_constraint(op.f('properties_slug_key'), 'properties', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_table('property_sequences')
    # ### end Alembic commands ###
