"""

Revision ID: be23287da1bd
Revises: ed7fbd404f8a
Create Date: 2026-07-24 14:15:22.741918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be23287da1bd'
down_revision: Union[str, Sequence[str], None] = 'ed7fbd404f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'created_from_lead_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'created_from_lead_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
