"""

Revision ID: e2a99564016f
Revises: 686247ca1d0a
Create Date: 2026-05-22 20:20:35.356486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a99564016f'
down_revision: Union[str, Sequence[str], None] = '686247ca1d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('properties', 'property_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'transaction_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'price_sale',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('properties', 'price_rent',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('properties', 'condominium_fee',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('properties', 'iptu',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('properties', 'iptu_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'bedrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'bathrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'garage_spots',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'area',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('properties', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'area',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('properties', 'garage_spots',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'bathrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'bedrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'iptu_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'iptu',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('properties', 'condominium_fee',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('properties', 'price_rent',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('properties', 'price_sale',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('properties', 'transaction_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'property_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
